language: python

python:
    - 3.5

install:
    - pip install -U -r test_requirements.txt
    - pip install -e .

script:
    - pycodestyle --exclude=tests,docs .
    - flake8 --exclude=tests,docs .
    - py.test --cov=anpy
after_script: coveralls
