language: python

env:
    # LEGIFRANCE_PROXY
    secure: bZzM5lesjVuJuPQ14zT90QJQizf+lmW6xU/HfQ2qfycZ1lwoZjwErqXsuv0MIsdgX4/syiw0uvpJ9/5lnnAboxPQcZiutGs4v7VtwVMUQvfyCLqHIdNm0EeTBexdKLEt+j7RUaMcETWasrthNTevfxAIZJYCzRB9bSZxEk02D78=

python:
    - 3.5

install:
    - pip install -U -r test_requirements.txt
    - pip install -e .

script:
    - pycodestyle --exclude=tests,docs .
    - flake8 --exclude=tests,docs .
    - py.test --cov=anpy
after_script: coveralls
