language: python

python:
    - 3.5

install:
    - pip install pytest flake8 pycodestyle
    - pip install -U setuptools>=18.5
    - pip install -e .

script:
    - pycodestyle --exclude=tests,docs .
    - flake8 --exclude=tests,docs .
    - py.test
